version: '3.7'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container usr/src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - mongodb_container
    environment:
      # DATABASE_URL: postgres://user:password@postgres:5432/db
      # NODE_ENV: development
      # JWT_SECRET: 1hard_to_guess_secret7890a
      PORT: 3000
    ports:
      - 8080:3000
      # debugging port
      - 9229:9229

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
